version: '3.8'

services:
  db:
    image: postgres
    restart: always
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=./config/local.yaml ./
    depends_on:
      - db