env: "local" # Окружение - local, dev или prod

http_server: # конфигурация http-сервера
  address: "localhost:8085"
  timeout: 4s
  idle_timeout: 30s

postgres:
  addr: "localhost:5432"
  user: "postgres"
  password: "postgres"
  database: "db"